### ISSUE TITLE
Remove alert on startup

### ISSUE THREAD

**Issue by funivan** [PrashntS/thunder-sync#3]
Add ability to show number of synced contacts in status row.
Change this code:
`alert("Synchronized "+number+" Contacts from the Server.");`
to 
`TABS_Class.putStatus("Synchronized "+number+" Contacts from the Server.");`
This alert is a annoying for some users. 
I can make PR =)

**Comment by prashnts** [comment]
Hi!
Sure, please go ahead!
This repository was just a little project I did as an assignment at my university - glad that it is useful to someone. Mozilla didn't have a very good documentation though.
